[package]
name = "obsidian-tidy"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["obsidian-tidy-core", "obsidian-tidy-logging"]

[workspace.dependencies]
tracing = "0.1"
anyhow = "1"
obsidian-tidy-logging = { path = "./obsidian-tidy-logging" }
obsidian-tidy-core = { path = "./obsidian-tidy-core" }

[dependencies]
tracing.workspace = true
obsidian-tidy-logging.workspace = true
