[package]
name = "obsidian-tidy-core"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0"
obsidian-parser.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
toml.workspace = true
